// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica2;

namespace Practica2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190613175358_InitialLast")]
    partial class InitialLast
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Practica2.Gasto", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("FechaRegistro");

                    b.Property<string>("IngresoAsociadoId");

                    b.Property<double>("Monto");

                    b.Property<string>("Nombre");

                    b.Property<int>("TipoTransaccion");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Gastos");
                });

            modelBuilder.Entity("Practica2.Ingreso", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion");

                    b.Property<string>("FechaEstimada");

                    b.Property<string>("FechaRegistro");

                    b.Property<double>("Monto");

                    b.Property<string>("Nombre");

                    b.Property<int>("TipoTransaccion");

                    b.Property<int?>("UsuarioId");

                    b.HasKey("ID");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Ingresos");
                });

            modelBuilder.Entity("Practica2.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("Practica2.Gasto", b =>
                {
                    b.HasOne("Practica2.Usuario")
                        .WithMany("Gastos")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("Practica2.Ingreso", b =>
                {
                    b.HasOne("Practica2.Usuario")
                        .WithMany("Ingresos")
                        .HasForeignKey("UsuarioId");
                });
#pragma warning restore 612, 618
        }
    }
}
